### ISSUE TITLE
what version of unity do i choose?

### ISSUE THREAD

**Issue by Jonnycatmeow** [Shattered-Devs/Unity-Party#1]
i have a mac so what version do i use for it the unity editor or the unity installer?

**Comment by reithegoat** [comment]
You should use Unity 2020.3.20. Though you're free to use any newer version
of Unity 2020, but earlier versions may cause the project to malfunction.

*Also, the project does not natively function for macOS. You might come
across issues while trying to play Unity Party in the macOS version of
Unity.*

**Comment by Jonnycatmeow** [comment]
yeah but like 
what do i choose the unity editor?

**Comment by Jonnycatmeow** [comment]
or something eles

**Comment by Jonnycatmeow** [comment]
or do i use unity hub?

**Comment by reithegoat** [comment]
Of course. Unity Hub is required to use any version of the Editor. The
Unity Hub can help you choose the version required by the project.
