### ISSUE TITLE
How to open Unity Party in Unity 2020.3.8f1(windows 10)

### ISSUE THREAD

**Issue by Ambijubi** [Shattered-Devs/Unity-Party#9]
I can't run game in Unity 2020.3.8f1, it throws an error
![QIP Shot - Screen 002](https://user-images.githubusercontent.com/95302846/187038716-fdb777cf-cced-41be-9712-2afbbe765b93.png)
.

**Comment by raonygamer** [comment]
u need to install GIT Scm and restart the system. https://git-scm.com/downloads

**Comment by Ambijubi** [comment]
Not working. :-(

**Comment by Linuxydable** [comment]
Unity Party only work with Unity 2021.3 LTS and above.

Thanks.
